
name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  PROJECT_ID: ${{secrets.RUN_PROJECT}}
  APP_ID: test-deploy
  RUN_REGION: europe-west1
  SA_KEY_JSON: ${{secrets.RUN_SA_KEY}}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-cloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{secrets.RUN_SA_KEY}}
          project_id: ${{secrets.RUN_PROJECT}}

      - name: Build
        run: gcloud builds submit --tag eu.gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image eu.gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --project=$PROJECT_ID --allow-unauthenticated
